import { useState, useMemo } from 'react';
import { Search, Plus, Trash2, Edit2, Check, X, ShieldAlert, BookOpen, AlertCircle, Filter, FilterX, ChevronDown, ChevronUp, Download, FileSpreadsheet } from 'lucide-react';
import { handleDownloadBaseExcel } from './exportUtils';
import { Riesgo } from '@/types';
import { useToast } from '@/components/ToastProvider';
import { MultiSelectDropdown } from '@/components/MultiSelectDropdown';
import { ExcelUploader } from './components/ExcelUploader';

interface BaseConocimientoProps {
  savedRiesgos: Riesgo[];
  onManualEntry: (riesgo: Riesgo) => void;
  onBulkEntry?: (riesgos: Riesgo[]) => void;
  onEditRiesgo: (updatedRiesgo: Riesgo) => Promise<void>;
  onDeleteRiesgo: (numero_riesgo: string) => void;
}

export default function BaseConocimiento({
  savedRiesgos,
  onManualEntry,
  onBulkEntry,
  onEditRiesgo,
  onDeleteRiesgo,
}: BaseConocimientoProps) {
  const { showToast } = useToast();
  const [searchTerm, setSearchTerm] = useState('');
  const [selectedTipoContrato, setSelectedTipoContrato] = useState("ALL");
  const [showFilters, setShowFilters] = useState(false);
  const [selectedSector, setSelectedSector] = useState("ALL");
  const [selectedCategoria, setSelectedCategoria] = useState("ALL");
  const [selectedSubcategoria, setSelectedSubcategoria] = useState("ALL");
  const [isAddingNew, setIsAddingNew] = useState(false);
  const [editingId, setEditingId] = useState<string | null>(null);
  const [expandedRows, setExpandedRows] = useState<Set<string>>(new Set());

  // Form states for manual addition
  const [newRiesgo, setNewRiesgo] = useState<any>({
    sector: [],
    tipo_contrato: '',
    categoria: '',
    subcategoria: '',
    riesgo_identificado: '',
    foco_revision: '',
    sustento_legal_normativo: '',
    nivel_sustento_documental: 'MANUAL',
    alerta_sistema: 'Ingresado de forma manual en biblioteca.',
  });

  const toggleRow = (numero_riesgo: string) => {
    setExpandedRows(prev => {
      const next = new Set(prev);
      if (next.has(numero_riesgo)) {
        next.delete(numero_riesgo);
      } else {
        next.add(numero_riesgo);
      }
      return next;
    });
  };

  // Edit states
  const [editForm, setEditForm] = useState<any>({});

  // Helper to check if a value matches a multi-select filter
  const matchesFilter = (value: string | undefined, filter: string[]) => {
    if (filter.length === 0) return true;
    if (!value) return false;
    const values = value.split(', ').map(v => v.trim().toUpperCase());
    return filter.some(f => values.includes(f.toUpperCase()));
  };

  
  const filterArrays = {
    sectores: Array.from(new Set(savedRiesgos.flatMap(r => r.sector ? r.sector.split(', ').map(s=>s.trim()) : []))).filter(Boolean).sort(),
    tiposContrato: Array.from(new Set(savedRiesgos.map(r => r.tipo_contrato))).filter(Boolean).sort(),
    categorias: Array.from(new Set(savedRiesgos.map(r => r.categoria))).filter(Boolean).sort(),
    subcategorias: Array.from(new Set(savedRiesgos.map(r => r.subcategoria))).filter(Boolean).sort(),
  };

  // For the 'Agregar Nuevo' form we need {label, value} format:
  const sectoresOptions = filterArrays.sectores.map(s => ({label: s, value: s}));


  const clearFilters = () => {
    setSearchTerm('');
    setSelectedTipoContrato('ALL');
    setSelectedSector('ALL');
    setSelectedCategoria('ALL');
    setSelectedSubcategoria('ALL');
  };

  // Handle addition
  const handleAddNewSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (!newRiesgo.riesgo_identificado?.trim()) {
      showToast('Por favor complete la descripción del riesgo.', 'warning');
      return;
    }
    const finalRiesgo: Riesgo = {
      numero_riesgo: '', // autogenerated in App
      sector: Array.isArray(newRiesgo.sector) ? newRiesgo.sector.join(', ') : (newRiesgo.sector || ''),
      tipo_contrato: newRiesgo.tipo_contrato || '',
      categoria: newRiesgo.categoria || '',
      subcategoria: newRiesgo.subcategoria || '',
      riesgo_identificado: newRiesgo.riesgo_identificado,
      foco_revision: newRiesgo.foco_revision || '',
      nombre_archivo_licitacion: newRiesgo.nombre_archivo_licitacion || '',
      seccion_bases: newRiesgo.seccion_bases || '',
      pagina_pdf: newRiesgo.pagina_pdf || null,
      nombre_archivo_normativa: newRiesgo.nombre_archivo_normativa || '',
      contexto_parrafo: newRiesgo.contexto_parrafo || '',
      evidencia_licitacion: newRiesgo.evidencia_licitacion || '',
      fragmento_literal_fuente: newRiesgo.fragmento_literal_fuente || '',
      sustento_legal_normativo: newRiesgo.sustento_legal_normativo || '',
      nivel_sustento_documental: newRiesgo.nivel_sustento_documental || 'MANUAL',
      alerta_sistema: newRiesgo.alerta_sistema || 'Ingresado de forma manual en biblioteca.',
      created_at: new Date().toISOString(),
      activo: true,
    };
    onManualEntry(finalRiesgo);
    setIsAddingNew(false);
    setNewRiesgo({
      sector: [],
      tipo_contrato: '',
      categoria: '',
      subcategoria: '',
      riesgo_identificado: '',
      foco_revision: '',
      nombre_archivo_licitacion: '',
      seccion_bases: '',
      pagina_pdf: undefined,
      nombre_archivo_normativa: '',
      contexto_parrafo: '',
      evidencia_licitacion: '',
      fragmento_literal_fuente: '',
      sustento_legal_normativo: '',
      nivel_sustento_documental: 'MANUAL',
      alerta_sistema: 'Ingresado de forma manual en biblioteca.',
    });
    showToast('Riesgo manual agregado con éxito.', 'success');
  };

  // Start edit mode
  const handleStartEdit = (riesgo: Riesgo) => {
    setEditingId(riesgo.numero_riesgo);
    const sectorArr = riesgo.sector ? riesgo.sector.split(', ') : [];
    setEditForm({ ...riesgo, sector: sectorArr as any });
  };

  // Cancel edit mode
  const handleCancelEdit = () => {
    setEditingId(null);
    setEditForm({});
  };

  // Submit edit
  const handleSaveEdit = async () => {
    if (!editForm.riesgo_identificado?.trim()) {
      showToast('La descripción del riesgo no puede estar vacía.', 'warning');
      return;
    }
    const finalEditForm = {
      ...editForm,
      sector: Array.isArray(editForm.sector) ? editForm.sector.join(', ') : (editForm.sector || '')
    };
    await onEditRiesgo(finalEditForm as Riesgo);
    setEditingId(null);
    setEditForm({});
    showToast('Riesgo actualizado con éxito.', 'success');
  };

  // Handle deletion
  const handleDelete = (numero_riesgo: string) => {
    onDeleteRiesgo(numero_riesgo);
  };

  // Filter list
  const filteredRiesgos = useMemo(() => {
    return savedRiesgos.filter(r => {
      const riesgoIdentificado = r.riesgo_identificado || '';
      const numeroRiesgo = r.numero_riesgo || '';
      const sustento = r.sustento_legal_normativo || '';
      
      const matchesSearch =
        riesgoIdentificado.toLowerCase().includes(searchTerm.toLowerCase()) ||
        numeroRiesgo.toLowerCase().includes(searchTerm.toLowerCase()) ||
        sustento.toLowerCase().includes(searchTerm.toLowerCase());
        
      const rSectors = r.sector ? r.sector.split(', ').map(s=>s.trim().toUpperCase()) : [];
      const matchesSector = selectedSector === "ALL" || rSectors.includes(selectedSector.toUpperCase());
      const matchesTipoContrato = selectedTipoContrato === "ALL" || (r.tipo_contrato || "").toUpperCase() === selectedTipoContrato.toUpperCase();
      const matchesCategoria = selectedCategoria === "ALL" || (r.categoria || "").toUpperCase() === selectedCategoria.toUpperCase();
      const matchesSubcategoria = selectedSubcategoria === "ALL" || (r.subcategoria || "").toUpperCase() === selectedSubcategoria.toUpperCase();

      return matchesSearch && matchesSector && matchesTipoContrato && matchesCategoria && matchesSubcategoria;
    });
  }, [savedRiesgos, searchTerm, selectedSector, selectedTipoContrato, selectedCategoria, selectedSubcategoria]);

  const activeFiltersCount = (selectedTipoContrato !== "ALL" ? 1 : 0) + (selectedSector !== "ALL" ? 1 : 0) + (selectedCategoria !== "ALL" ? 1 : 0) + (selectedSubcategoria !== "ALL" ? 1 : 0);


  return (
    <div className="w-full space-y-6 animate-fade-in">
      {/* Title section */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div>
          <h1 className="text-2xl sm:text-3xl font-extrabold text-slate-900 tracking-tight flex items-center gap-3">
            <BookOpen className="w-8 h-8 text-indigo-600" />
            Base de Conocimiento
          </h1>
          <p className="text-sm text-slate-500 mt-1">
            Biblioteca local y repositorio de riesgos alimentados por análisis automatizados y registros manuales.
          </p>
        </div>
        <button
          onClick={() => setIsAddingNew(!isAddingNew)}
          className="flex items-center justify-center gap-2 px-5 py-2.5 text-indigo-600 hover:bg-indigo-50 font-semibold text-sm rounded-xl transition-colors cursor-pointer"
        >
          {isAddingNew ? <X className="w-4 h-4" /> : <Plus className="w-4 h-4" />}
          {isAddingNew ? 'Cancelar' : 'Importar Excel'}
        </button>
      </div>

      {/* Manual creation form */}
      {isAddingNew && (
        <ExcelUploader 
          onImport={(riesgos) => {
            if (onBulkEntry) onBulkEntry(riesgos);
            setIsAddingNew(false);
          }} 
          onCancel={() => setIsAddingNew(false)} 
        />
      )}

      {/* Filter and Search Bar */}
      
      {/* Filter and Search Bar */}
      <div className="flex flex-col gap-4">
        {/* Top row: Search and filter toggle */}
        <div className="flex flex-col md:flex-row gap-3 items-center justify-between">
          <div className="flex flex-col md:flex-row gap-3 items-center w-full md:w-auto flex-1">
            <div className="relative w-full md:w-96">
              <Search className="absolute left-3.5 top-2.5 w-4 h-4 text-slate-400" />
              <input
                type="text"
                placeholder="Buscar por código, descripción o sustento legal..."
                value={searchTerm}
                onChange={(e) => setSearchTerm(e.target.value)}
                className="w-full pl-10 pr-4 py-2 bg-white border border-slate-200 rounded-xl text-sm focus:outline-none focus:ring-2 focus:ring-indigo-500/20 focus:border-indigo-500 transition-all"
              />
            </div>
            <button
              onClick={() => setShowFilters(!showFilters)}
              className={`flex items-center justify-center gap-2 px-4 py-2 rounded-xl text-sm font-bold transition-all border ${activeFiltersCount > 0 || showFilters ? "bg-indigo-100 text-indigo-700 border-transparent" : "bg-white border-slate-200 text-slate-600 hover:bg-slate-50"}`}
            >
              <Filter className="w-4 h-4" />
              Filtros {activeFiltersCount > 0 && `(${activeFiltersCount})`}
            </button>
            {activeFiltersCount > 0 && (
              <button
                onClick={clearFilters}
                className="flex items-center gap-2 px-4 py-2 text-sm font-medium text-slate-600 hover:text-slate-800 bg-slate-100 hover:bg-slate-200 rounded-xl transition-colors shrink-0"
                title="Limpiar filtros"
              >
                <FilterX className="w-4 h-4" />
              </button>
            )}
          </div>
          <button
            onClick={() => handleDownloadBaseExcel(filteredRiesgos)}
            className="inline-flex items-center justify-center gap-2 px-4 py-2 bg-emerald-600 hover:bg-emerald-700 text-white text-xs font-bold rounded-xl transition-colors shadow-sm cursor-pointer w-full md:w-auto"
          >
            <FileSpreadsheet className="w-4 h-4" />
            DESCARGAR EXCEL
          </button>
        </div>

        {/* Filters */}
        {showFilters && (
          <div className="flex flex-wrap items-center gap-3 animate-in slide-in-from-top-2 duration-200">
            <div className={`relative flex items-center px-3 py-1.5 rounded-full transition-colors border ${selectedTipoContrato !== "ALL" ? "bg-indigo-100 text-indigo-700 border-transparent" : "bg-transparent border-transparent hover:bg-slate-100 text-slate-600"}`}>
              <select
                value={selectedTipoContrato}
                onChange={(e) => setSelectedTipoContrato(e.target.value)}
                className="appearance-none bg-transparent border-none outline-none focus:outline-none focus:ring-0 text-sm font-medium cursor-pointer pr-6"
              >
                <option value="ALL">Tipos de Contrato</option>
                {filterArrays.tiposContrato.map((t) => (
                  <option key={t} value={t}>{t}</option>
                ))}
              </select>
              {selectedTipoContrato !== "ALL" ? (
                <button onClick={() => setSelectedTipoContrato("ALL")} className="absolute right-2 p-0.5 rounded-full hover:bg-indigo-200 text-indigo-500 hover:text-indigo-700 z-10" title="Quitar filtro">
                  <X className="w-3 h-3" />
                </button>
              ) : (
                <ChevronDown className="absolute right-2 w-3 h-3 pointer-events-none opacity-50" />
              )}
            </div>

            <div className={`relative flex items-center px-3 py-1.5 rounded-full transition-colors border ${selectedSector !== "ALL" ? "bg-indigo-100 text-indigo-700 border-transparent" : "bg-transparent border-transparent hover:bg-slate-100 text-slate-600"}`}>
              <select
                value={selectedSector}
                onChange={(e) => setSelectedSector(e.target.value)}
                className="appearance-none bg-transparent border-none outline-none focus:outline-none focus:ring-0 text-sm font-medium cursor-pointer pr-6"
              >
                <option value="ALL">Sectores</option>
                {filterArrays.sectores.map((s) => (
                  <option key={s} value={s}>{s}</option>
                ))}
              </select>
              {selectedSector !== "ALL" ? (
                <button onClick={() => setSelectedSector("ALL")} className="absolute right-2 p-0.5 rounded-full hover:bg-indigo-200 text-indigo-500 hover:text-indigo-700 z-10" title="Quitar filtro">
                  <X className="w-3 h-3" />
                </button>
              ) : (
                <ChevronDown className="absolute right-2 w-3 h-3 pointer-events-none opacity-50" />
              )}
            </div>

            <div className={`relative flex items-center px-3 py-1.5 rounded-full transition-colors border ${selectedCategoria !== "ALL" ? "bg-indigo-100 text-indigo-700 border-transparent" : "bg-transparent border-transparent hover:bg-slate-100 text-slate-600"}`}>
              <select
                value={selectedCategoria}
                onChange={(e) => setSelectedCategoria(e.target.value)}
                className="appearance-none bg-transparent border-none outline-none focus:outline-none focus:ring-0 text-sm font-medium cursor-pointer pr-6"
              >
                <option value="ALL">Categorías</option>
                {filterArrays.categorias.map((c) => (
                  <option key={c} value={c}>{c}</option>
                ))}
              </select>
              {selectedCategoria !== "ALL" ? (
                <button onClick={() => setSelectedCategoria("ALL")} className="absolute right-2 p-0.5 rounded-full hover:bg-indigo-200 text-indigo-500 hover:text-indigo-700 z-10" title="Quitar filtro">
                  <X className="w-3 h-3" />
                </button>
              ) : (
                <ChevronDown className="absolute right-2 w-3 h-3 pointer-events-none opacity-50" />
              )}
            </div>

            <div className={`relative flex items-center px-3 py-1.5 rounded-full transition-colors border ${selectedSubcategoria !== "ALL" ? "bg-indigo-100 text-indigo-700 border-transparent" : "bg-transparent border-transparent hover:bg-slate-100 text-slate-600"}`}>
              <select
                value={selectedSubcategoria}
                onChange={(e) => setSelectedSubcategoria(e.target.value)}
                className="appearance-none bg-transparent border-none outline-none focus:outline-none focus:ring-0 text-sm font-medium cursor-pointer pr-6"
              >
                <option value="ALL">Subcategorías</option>
                {filterArrays.subcategorias.map((s) => (
                  <option key={s} value={s}>{s}</option>
                ))}
              </select>
              {selectedSubcategoria !== "ALL" ? (
                <button onClick={() => setSelectedSubcategoria("ALL")} className="absolute right-2 p-0.5 rounded-full hover:bg-indigo-200 text-indigo-500 hover:text-indigo-700 z-10" title="Quitar filtro">
                  <X className="w-3 h-3" />
                </button>
              ) : (
                <ChevronDown className="absolute right-2 w-3 h-3 pointer-events-none opacity-50" />
              )}
            </div>
          </div>
        )}
      </div>

      {/* Table Results */}
      {filteredRiesgos.length === 0 ? (
        <div className="bg-white rounded-2xl border border-slate-200 shadow-sm p-12 text-center max-w-md mx-auto">
          <ShieldAlert className="w-12 h-12 text-slate-300 mx-auto mb-4" />
          <h3 className="text-lg font-bold text-slate-800">Sin resultados</h3>
          <p className="text-sm text-slate-500 mt-2">
            No encontramos ningún riesgo que coincida con los filtros aplicados o tu consulta actual.
          </p>
        </div>
      ) : (
        <div className="bg-white rounded-2xl border border-slate-200 shadow-sm overflow-hidden animate-fade-in relative z-0">
          <div className="overflow-x-auto w-full">
            <table className="w-full text-left text-sm whitespace-nowrap min-w-max">
              <thead className="bg-slate-100 text-slate-600 font-bold border-b border-slate-200 text-xs uppercase tracking-wider">
                <tr>
                  <th className="p-4 sticky left-0 z-10 bg-slate-100">Código</th>
                  <th className="p-4">Tipo Contrato</th>
                  <th className="p-4">Sector</th>
                  <th className="p-4">Categoría</th>
                  <th className="p-4">Subcategoría</th>
                  <th className="p-4 min-w-[300px]">Riesgo Identificado</th>
                  <th className="p-4 min-w-[200px]">Foco Revisión</th>
                  <th className="p-4 min-w-[300px]">Sustento Legal y Contexto</th>
                  <th className="p-4 text-center">Nivel Sustento</th>
                  <th className="p-4 text-right sticky right-0 z-10 shadow-[-4px_0_10px_-4px_rgba(0,0,0,0.05)] bg-slate-100">Acciones</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-100">
                {filteredRiesgos.map((riesgo, idx) => {
                  const isEditing = editingId === riesgo.numero_riesgo;
                  
                                    if (isEditing) {
                    return (
                      <tr key={riesgo.numero_riesgo} className="bg-indigo-50/50">
                        <td className="p-4 font-mono text-indigo-600 font-bold sticky left-0 z-10 bg-indigo-50" style={{ backgroundColor: '#eef2ff' }}>
                          {riesgo.numero_riesgo}
                        </td>
                        <td className="p-4 align-top">
                          <input type="text" value={editForm.tipo_contrato || ''} onChange={e => setEditForm({ ...editForm, tipo_contrato: e.target.value })} className="w-full min-w-[120px] px-2 py-1.5 border border-slate-300 bg-white rounded-lg text-sm focus:ring-1 focus:ring-indigo-500" />
                        </td>
                        <td className="p-4 align-top">
                          <input type="text" value={Array.isArray(editForm.sector) ? editForm.sector.join(', ') : (editForm.sector || '')} onChange={e => setEditForm({ ...editForm, sector: e.target.value.split(',').map(s=>s.trim()) })} className="w-full min-w-[120px] px-2 py-1.5 border border-slate-300 bg-white rounded-lg text-sm focus:ring-1 focus:ring-indigo-500" placeholder="Sec1, Sec2" />
                        </td>
                        <td className="p-4 align-top">
                          <input type="text" value={editForm.categoria || ''} onChange={e => setEditForm({ ...editForm, categoria: e.target.value })} className="w-full min-w-[120px] px-2 py-1.5 border border-slate-300 bg-white rounded-lg text-sm focus:ring-1 focus:ring-indigo-500" />
                        </td>
                        <td className="p-4 align-top">
                          <input type="text" value={editForm.subcategoria || ''} onChange={e => setEditForm({ ...editForm, subcategoria: e.target.value })} className="w-full min-w-[120px] px-2 py-1.5 border border-slate-300 bg-white rounded-lg text-sm focus:ring-1 focus:ring-indigo-500" />
                        </td>
                        <td className="p-4 align-top">
                          <textarea value={editForm.riesgo_identificado || ''} onChange={e => setEditForm({ ...editForm, riesgo_identificado: e.target.value })} className="w-full min-w-[300px] px-2 py-1.5 border border-slate-300 bg-white rounded-lg text-sm resize-none focus:ring-1 focus:ring-indigo-500 whitespace-normal" rows={4} />
                        </td>
                        <td className="p-4 align-top">
                          <textarea value={editForm.foco_revision || ''} onChange={e => setEditForm({ ...editForm, foco_revision: e.target.value })} className="w-full min-w-[200px] px-2 py-1.5 border border-slate-300 bg-white rounded-lg text-sm resize-none focus:ring-1 focus:ring-indigo-500 whitespace-normal" rows={4} />
                        </td>
                        <td className="p-4 align-top">
                          <textarea value={editForm.sustento_legal_normativo || ''} onChange={e => setEditForm({ ...editForm, sustento_legal_normativo: e.target.value })} className="w-full min-w-[300px] px-2 py-1.5 border border-slate-300 bg-white rounded-lg text-sm resize-none focus:ring-1 focus:ring-indigo-500 whitespace-normal" rows={4} />
                        </td>
                        <td className="p-4 align-top">
                          <select value={editForm.nivel_sustento_documental || ''} onChange={e => setEditForm({ ...editForm, nivel_sustento_documental: e.target.value })} className="w-full px-2 py-1.5 border border-slate-300 bg-white rounded-lg text-sm focus:ring-1 focus:ring-indigo-500">
                             <option value="">Seleccione</option>
                             <option value="ALTO">ALTO</option>
                             <option value="MEDIO">MEDIO</option>
                             <option value="BAJO">BAJO</option>
                          </select>
                        </td>
                        <td className="p-4 text-right sticky right-0 z-10 shadow-[-4px_0_10px_-4px_rgba(0,0,0,0.05)] bg-indigo-50" style={{ backgroundColor: '#eef2ff' }}>
                          <div className="flex items-center justify-end gap-1">
                            <button onClick={handleSaveEdit} className="p-1.5 bg-emerald-100 text-emerald-700 hover:bg-emerald-200 rounded-lg transition-colors cursor-pointer" title="Guardar Cambios">
                              <Check className="w-4 h-4" />
                            </button>
                            <button onClick={handleCancelEdit} className="p-1.5 bg-slate-200 text-slate-700 hover:bg-slate-300 rounded-lg transition-colors cursor-pointer" title="Cancelar">
                              <X className="w-4 h-4" />
                            </button>
                          </div>
                        </td>
                      </tr>
                    );
                  }

                  return (
                    <tr key={riesgo.numero_riesgo} className={idx % 2 === 0 ? 'bg-white hover:bg-slate-50 transition-colors' : 'bg-slate-50 hover:bg-slate-100 transition-colors'}>
                      <td className="p-4 font-mono text-indigo-600 font-bold sticky left-0 z-10 shadow-[4px_0_10px_-4px_rgba(0,0,0,0.05)]" style={{ backgroundColor: 'inherit' }}>
                        {riesgo.numero_riesgo}
                      </td>
                      <td className="p-4"><span className="px-2 py-1 bg-slate-100 text-slate-600 rounded-lg text-xs font-semibold">{riesgo.tipo_contrato || "-"}</span></td>
                      <td className="p-4"><span className="px-2 py-1 bg-slate-100 text-slate-600 rounded-lg text-xs font-semibold">{riesgo.sector || "-"}</span></td>
                      <td className="p-4"><span className="px-2 py-1 bg-indigo-50 text-indigo-600 rounded-lg text-xs font-semibold">{riesgo.categoria || "-"}</span></td>
                      <td className="p-4">{riesgo.subcategoria ? <span className="px-2 py-1 bg-indigo-50 text-indigo-600 rounded-lg text-xs font-semibold">{riesgo.subcategoria}</span> : "-"}</td>
                      <td className="p-4">
                        <div className="font-semibold text-slate-800 whitespace-normal break-words max-w-sm">
                          {riesgo.riesgo_identificado || "-"}
                        </div>
                      </td>
                      <td className="p-4 whitespace-normal break-words max-w-[250px] text-slate-600 text-sm">
                        {riesgo.foco_revision || "-"}
                      </td>
                      <td className="p-4 whitespace-normal break-words max-w-sm text-slate-600 text-sm">
                        {riesgo.sustento_legal_normativo ? (
                          <div className="line-clamp-3 hover:line-clamp-none transition-all">{riesgo.sustento_legal_normativo}</div>
                        ) : (
                          <span className="text-slate-400 italic">No se ingresó sustento</span>
                        )}
                      </td>
                      <td className="p-4 text-center">
                        <span className={`px-2 py-1 rounded-full text-xs font-bold ${
                          riesgo.nivel_sustento_documental?.toUpperCase() === "ALTO" ? "bg-emerald-100 text-emerald-700" :
                          riesgo.nivel_sustento_documental?.toUpperCase() === "MEDIO" ? "bg-amber-100 text-amber-700" :
                          "bg-slate-100 text-slate-700"
                        }`}>
                          {riesgo.nivel_sustento_documental || "N/A"}
                        </span>
                      </td>
                      <td className="p-4 sticky right-0 z-10 shadow-[-4px_0_10px_-4px_rgba(0,0,0,0.05)]" style={{ backgroundColor: 'inherit' }}>
                        <div className="flex items-center justify-end gap-1">
                          <button
                            onClick={(e) => { e.stopPropagation(); handleStartEdit(riesgo); }}
                            className="p-1.5 text-slate-400 hover:text-indigo-600 hover:bg-indigo-50 rounded-lg transition-colors cursor-pointer"
                            title="Editar Riesgo"
                          >
                            <Edit2 className="w-4 h-4" />
                          </button>
                          <button
                            onClick={(e) => { e.stopPropagation(); handleDelete(riesgo.numero_riesgo); }}
                            className="p-1.5 text-slate-400 hover:text-rose-600 hover:bg-rose-50 rounded-lg transition-colors cursor-pointer"
                            title="Eliminar de Biblioteca"
                          >
                            <Trash2 className="w-4 h-4" />
                          </button>
                        </div>
                      </td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </div>
        </div>
      )}
    </div>
  );
}
