import { useState, useMemo } from 'react';
import { Search, Plus, Trash2, Edit2, Check, X, ShieldAlert, BookOpen, AlertCircle, Filter } from 'lucide-react';
import { Riesgo } from '../types';
import { useToast } from '../components/ToastProvider';

interface BaseConocimientoProps {
  savedRiesgos: Riesgo[];
  onManualEntry: (riesgo: Riesgo) => void;
  onEditRiesgo: (updatedRiesgo: Riesgo) => Promise<void>;
  onDeleteRiesgo: (numero_riesgo: string) => Promise<void>;
}

export default function BaseConocimiento({
  savedRiesgos,
  onManualEntry,
  onEditRiesgo,
  onDeleteRiesgo,
}: BaseConocimientoProps) {
  const { showToast } = useToast();
  const [searchTerm, setSearchTerm] = useState('');
  const [selectedSector, setSelectedSector] = useState('ALL');
  const [selectedCategoria, setSelectedCategoria] = useState('ALL');
  const [isAddingNew, setIsAddingNew] = useState(false);
  const [editingId, setEditingId] = useState<string | null>(null);

  // Form states for manual addition
  const [newRiesgo, setNewRiesgo] = useState<Partial<Riesgo>>({
    sector: 'PÚBLICO',
    tipo_contrato: 'CONSTRUCCION',
    categoria: 'LEGAL',
    subcategoria: 'CONTROVERSIAS',
    riesgo_identificado: '',
    foco_revision: 'ADMINISTRATIVO',
    sustento_legal_normativo: '',
    nivel_sustento_documental: 'MANUAL',
    alerta_sistema: 'Ingresado de forma manual en biblioteca.',
  });

  // Edit states
  const [editForm, setEditForm] = useState<Partial<Riesgo>>({});

  // Filter options lists
  const sectores = useMemo(() => ['ALL', ...Array.from(new Set(savedRiesgos.map(r => r.sector)))].filter(Boolean), [savedRiesgos]);
  const categorias = useMemo(() => ['ALL', ...Array.from(new Set(savedRiesgos.map(r => r.categoria)))].filter(Boolean), [savedRiesgos]);

  // Handle addition
  const handleAddNewSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (!newRiesgo.riesgo_identificado?.trim()) {
      showToast('Por favor complete la descripción del riesgo.', 'warning');
      return;
    }
    const finalRiesgo: Riesgo = {
      numero_riesgo: '', // autogenerated in App
      sector: newRiesgo.sector || 'PÚBLICO',
      tipo_contrato: newRiesgo.tipo_contrato || 'CONSTRUCCION',
      categoria: newRiesgo.categoria || 'LEGAL',
      subcategoria: newRiesgo.subcategoria || 'CONTROVERSIAS',
      riesgo_identificado: newRiesgo.riesgo_identificado,
      foco_revision: newRiesgo.foco_revision || 'ADMINISTRATIVO',
      sustento_legal_normativo: newRiesgo.sustento_legal_normativo || '',
      nivel_sustento_documental: 'MANUAL',
      alerta_sistema: newRiesgo.alerta_sistema || 'Ingresado de forma manual.',
      created_at: new Date().toISOString(),
      activo: true,
    };
    onManualEntry(finalRiesgo);
    setIsAddingNew(false);
    setNewRiesgo({
      sector: 'PÚBLICO',
      tipo_contrato: 'CONSTRUCCION',
      categoria: 'LEGAL',
      subcategoria: 'CONTROVERSIAS',
      riesgo_identificado: '',
      foco_revision: 'ADMINISTRATIVO',
      sustento_legal_normativo: '',
      nivel_sustento_documental: 'MANUAL',
      alerta_sistema: 'Ingresado de forma manual en biblioteca.',
    });
    showToast('Riesgo manual agregado con éxito.', 'success');
  };

  // Start edit mode
  const handleStartEdit = (riesgo: Riesgo) => {
    setEditingId(riesgo.numero_riesgo);
    setEditForm({ ...riesgo });
  };

  // Cancel edit mode
  const handleCancelEdit = () => {
    setEditingId(null);
    setEditForm({});
  };

  // Submit edit
  const handleSaveEdit = async () => {
    if (!editForm.riesgo_identificado?.trim()) {
      showToast('La descripción del riesgo no puede estar vacía.', 'warning');
      return;
    }
    await onEditRiesgo(editForm as Riesgo);
    setEditingId(null);
    setEditForm({});
    showToast('Riesgo actualizado con éxito.', 'success');
  };

  // Handle deletion
  const handleDelete = async (numero_riesgo: string) => {
    if (confirm('¿Está seguro de que desea eliminar este riesgo de la base de conocimiento?')) {
      await onDeleteRiesgo(numero_riesgo);
      showToast('Riesgo eliminado de la biblioteca.', 'success');
    }
  };

  // Filter list
  const filteredRiesgos = useMemo(() => {
    return savedRiesgos.filter(r => {
      const matchesSearch =
        r.riesgo_identificado.toLowerCase().includes(searchTerm.toLowerCase()) ||
        r.numero_riesgo.toLowerCase().includes(searchTerm.toLowerCase()) ||
        (r.sustento_legal_normativo || '').toLowerCase().includes(searchTerm.toLowerCase());
      
      const matchesSector = selectedSector === 'ALL' || r.sector === selectedSector;
      const matchesCategoria = selectedCategoria === 'ALL' || r.categoria === selectedCategoria;

      return matchesSearch && matchesSector && matchesCategoria;
    });
  }, [savedRiesgos, searchTerm, selectedSector, selectedCategoria]);

  return (
    <div className="space-y-6 max-w-7xl mx-auto">
      {/* Title section */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div>
          <h1 className="text-2xl sm:text-3xl font-extrabold text-slate-900 tracking-tight flex items-center gap-3">
            <BookOpen className="w-8 h-8 text-indigo-600" />
            Base de Conocimiento
          </h1>
          <p className="text-sm text-slate-500 mt-1">
            Biblioteca local y repositorio de riesgos alimentados por análisis automatizados y registros manuales.
          </p>
        </div>
        <button
          onClick={() => setIsAddingNew(!isAddingNew)}
          className="flex items-center justify-center gap-2 px-5 py-2.5 bg-indigo-600 hover:bg-indigo-700 text-white font-semibold text-sm rounded-xl shadow-sm transition-colors cursor-pointer"
        >
          {isAddingNew ? <X className="w-4 h-4" /> : <Plus className="w-4 h-4" />}
          {isAddingNew ? 'Cancelar Registro' : 'Registrar Riesgo'}
        </button>
      </div>

      {/* Manual creation form */}
      {isAddingNew && (
        <form onSubmit={handleAddNewSubmit} className="bg-white rounded-2xl border border-slate-200 shadow-sm p-6 sm:p-8 space-y-5 animate-fade-in">
          <h2 className="text-lg font-bold text-slate-900">Agregar Nuevo Riesgo Manual</h2>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-5">
            <div>
              <label className="block text-sm font-medium text-slate-700 mb-1.5">Sector *</label>
              <select
                value={newRiesgo.sector}
                onChange={e => setNewRiesgo({ ...newRiesgo, sector: e.target.value })}
                className="w-full px-3.5 py-2 border border-slate-200 rounded-xl text-sm focus:outline-none focus:ring-2 focus:ring-indigo-500/20 focus:border-indigo-500"
              >
                <option value="PÚBLICO">Público</option>
                <option value="PRIVADO">Privado</option>
              </select>
            </div>
            <div>
              <label className="block text-sm font-medium text-slate-700 mb-1.5">Tipo de Contrato *</label>
              <select
                value={newRiesgo.tipo_contrato}
                onChange={e => setNewRiesgo({ ...newRiesgo, tipo_contrato: e.target.value })}
                className="w-full px-3.5 py-2 border border-slate-200 rounded-xl text-sm focus:outline-none focus:ring-2 focus:ring-indigo-500/20 focus:border-indigo-500"
              >
                <option value="CONSTRUCCION">Construcción</option>
                <option value="OXI">Obras por Impuestos (OxI)</option>
                <option value="APP">Asociación Público Privada (APP)</option>
                <option value="CONCESION">Concesión</option>
              </select>
            </div>
            <div>
              <label className="block text-sm font-medium text-slate-700 mb-1.5">Categoría *</label>
              <select
                value={newRiesgo.categoria}
                onChange={e => setNewRiesgo({ ...newRiesgo, categoria: e.target.value })}
                className="w-full px-3.5 py-2 border border-slate-200 rounded-xl text-sm focus:outline-none focus:ring-2 focus:ring-indigo-500/20 focus:border-indigo-500"
              >
                <option value="LEGAL">Legal</option>
                <option value="TÉCNICO">Técnico</option>
                <option value="FINANCIERO">Financiero</option>
                <option value="AMBIENTAL">Ambiental</option>
              </select>
            </div>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-5">
            <div>
              <label className="block text-sm font-medium text-slate-700 mb-1.5">Subcategoría</label>
              <input
                type="text"
                value={newRiesgo.subcategoria}
                onChange={e => setNewRiesgo({ ...newRiesgo, subcategoria: e.target.value })}
                className="w-full px-3.5 py-2 border border-slate-200 rounded-xl text-sm focus:outline-none focus:ring-2 focus:ring-indigo-500/20 focus:border-indigo-500"
                placeholder="Ej. CONTROVERSIAS"
              />
            </div>
            <div>
              <label className="block text-sm font-medium text-slate-700 mb-1.5">Foco de Revisión</label>
              <input
                type="text"
                value={newRiesgo.foco_revision}
                onChange={e => setNewRiesgo({ ...newRiesgo, foco_revision: e.target.value })}
                className="w-full px-3.5 py-2 border border-slate-200 rounded-xl text-sm focus:outline-none focus:ring-2 focus:ring-indigo-500/20 focus:border-indigo-500"
                placeholder="Ej. TECNICO"
              />
            </div>
          </div>

          <div>
            <label className="block text-sm font-medium text-slate-700 mb-1.5">Descripción del Riesgo Identificado *</label>
            <textarea
              rows={3}
              value={newRiesgo.riesgo_identificado}
              onChange={e => setNewRiesgo({ ...newRiesgo, riesgo_identificado: e.target.value })}
              className="w-full px-3.5 py-2 border border-slate-200 rounded-xl text-sm focus:outline-none focus:ring-2 focus:ring-indigo-500/20 focus:border-indigo-500"
              placeholder="Describa el hallazgo o contingencia legal/técnica..."
            />
          </div>

          <div>
            <label className="block text-sm font-medium text-slate-700 mb-1.5">Sustento Legal / Normativa (Opcional)</label>
            <textarea
              rows={3}
              value={newRiesgo.sustento_legal_normativo || ''}
              onChange={e => setNewRiesgo({ ...newRiesgo, sustento_legal_normativo: e.target.value })}
              className="w-full px-3.5 py-2 border border-slate-200 rounded-xl text-sm focus:outline-none focus:ring-2 focus:ring-indigo-500/20 focus:border-indigo-500"
              placeholder="Leyes, reglamentos o bases que sustentan este riesgo..."
            />
          </div>

          <div className="flex justify-end gap-3 pt-2">
            <button
              type="button"
              onClick={() => setIsAddingNew(false)}
              className="px-4 py-2 border border-slate-200 rounded-xl text-slate-700 text-sm font-semibold hover:bg-slate-50 transition-colors cursor-pointer"
            >
              Cancelar
            </button>
            <button
              type="submit"
              className="px-5 py-2 bg-indigo-600 hover:bg-indigo-700 text-white text-sm font-semibold rounded-xl shadow-sm transition-colors cursor-pointer"
            >
              Guardar en Biblioteca
            </button>
          </div>
        </form>
      )}

      {/* Filter and Search Bar */}
      <div className="bg-white rounded-2xl border border-slate-200 shadow-sm p-4 flex flex-col md:flex-row gap-4 items-center">
        {/* Search */}
        <div className="relative w-full md:flex-1">
          <Search className="absolute left-3.5 top-3 w-4 h-4 text-slate-400" />
          <input
            type="text"
            placeholder="Buscar por código, descripción o sustento legal..."
            value={searchTerm}
            onChange={e => setSearchTerm(e.target.value)}
            className="w-full pl-10 pr-4 py-2 bg-slate-50 border border-slate-200 rounded-xl text-sm focus:outline-none focus:ring-2 focus:ring-indigo-500/20 focus:border-indigo-500 placeholder-slate-400 transition-all focus:bg-white"
          />
        </div>

        {/* Sector Filter */}
        <div className="flex items-center gap-2 w-full md:w-auto shrink-0">
          <Filter className="w-4 h-4 text-slate-400" />
          <select
            value={selectedSector}
            onChange={e => setSelectedSector(e.target.value)}
            className="w-full md:w-40 px-3 py-2 bg-slate-50 border border-slate-200 rounded-xl text-sm focus:outline-none focus:ring-2 focus:ring-indigo-500/20 focus:border-indigo-500"
          >
            {sectores.map((sec) => (
              <option key={sec} value={sec}>{sec === 'ALL' ? 'Todos los Sectores' : sec}</option>
            ))}
          </select>
        </div>

        {/* Category Filter */}
        <div className="flex items-center gap-2 w-full md:w-auto shrink-0">
          <select
            value={selectedCategoria}
            onChange={e => setSelectedCategoria(e.target.value)}
            className="w-full md:w-44 px-3 py-2 bg-slate-50 border border-slate-200 rounded-xl text-sm focus:outline-none focus:ring-2 focus:ring-indigo-500/20 focus:border-indigo-500"
          >
            {categorias.map((cat) => (
              <option key={cat} value={cat}>{cat === 'ALL' ? 'Todas las Categorías' : cat}</option>
            ))}
          </select>
        </div>
      </div>

      {/* List results */}
      {filteredRiesgos.length === 0 ? (
        <div className="bg-white rounded-2xl border border-slate-200 shadow-sm p-12 text-center max-w-md mx-auto">
          <ShieldAlert className="w-12 h-12 text-slate-300 mx-auto mb-4" />
          <h3 className="text-lg font-bold text-slate-800">Sin resultados</h3>
          <p className="text-sm text-slate-500 mt-2">
            No encontramos ningún riesgo que coincida con los filtros aplicados o tu consulta actual.
          </p>
        </div>
      ) : (
        <div className="space-y-4">
          {filteredRiesgos.map((riesgo) => {
            const isEditing = editingId === riesgo.numero_riesgo;
            return (
              <div
                key={riesgo.numero_riesgo}
                className={`bg-white rounded-2xl border transition-all p-5 sm:p-6 ${
                  isEditing ? 'border-indigo-500 ring-2 ring-indigo-500/15 shadow-md' : 'border-slate-200 hover:border-slate-300 shadow-sm'
                }`}
              >
                {isEditing ? (
                  /* EDITING MODE FORM */
                  <div className="space-y-4 animate-fade-in">
                    <div className="flex items-center justify-between border-b border-slate-100 pb-3 mb-4">
                      <span className="text-sm font-mono font-bold text-slate-500">{riesgo.numero_riesgo}</span>
                      <div className="flex gap-2">
                        <button
                          onClick={handleSaveEdit}
                          className="p-1.5 bg-emerald-50 text-emerald-700 hover:bg-emerald-100 rounded-lg transition-colors cursor-pointer"
                          title="Guardar Cambios"
                        >
                          <Check className="w-4 h-4" />
                        </button>
                        <button
                          onClick={handleCancelEdit}
                          className="p-1.5 bg-slate-50 text-slate-600 hover:bg-slate-100 rounded-lg transition-colors cursor-pointer"
                          title="Cancelar"
                        >
                          <X className="w-4 h-4" />
                        </button>
                      </div>
                    </div>

                    <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                      <div>
                        <label className="block text-xs font-semibold text-slate-500 uppercase tracking-wider mb-1">Sector</label>
                        <select
                          value={editForm.sector || ''}
                          onChange={e => setEditForm({ ...editForm, sector: e.target.value })}
                          className="w-full px-3 py-1.5 border border-slate-200 rounded-xl text-sm"
                        >
                          <option value="PÚBLICO">PÚBLICO</option>
                          <option value="PRIVADO">PRIVADO</option>
                        </select>
                      </div>
                      <div>
                        <label className="block text-xs font-semibold text-slate-500 uppercase tracking-wider mb-1">Contrato</label>
                        <input
                          type="text"
                          value={editForm.tipo_contrato || ''}
                          onChange={e => setEditForm({ ...editForm, tipo_contrato: e.target.value })}
                          className="w-full px-3 py-1.5 border border-slate-200 rounded-xl text-sm"
                        />
                      </div>
                      <div>
                        <label className="block text-xs font-semibold text-slate-500 uppercase tracking-wider mb-1">Categoría</label>
                        <input
                          type="text"
                          value={editForm.categoria || ''}
                          onChange={e => setEditForm({ ...editForm, categoria: e.target.value })}
                          className="w-full px-3 py-1.5 border border-slate-200 rounded-xl text-sm"
                        />
                      </div>
                    </div>

                    <div>
                      <label className="block text-xs font-semibold text-slate-500 uppercase tracking-wider mb-1">Riesgo Identificado</label>
                      <textarea
                        rows={2}
                        value={editForm.riesgo_identificado || ''}
                        onChange={e => setEditForm({ ...editForm, riesgo_identificado: e.target.value })}
                        className="w-full px-3 py-1.5 border border-slate-200 rounded-xl text-sm"
                      />
                    </div>

                    <div>
                      <label className="block text-xs font-semibold text-slate-500 uppercase tracking-wider mb-1">Sustento Legal / Normativa</label>
                      <textarea
                        rows={2}
                        value={editForm.sustento_legal_normativo || ''}
                        onChange={e => setEditForm({ ...editForm, sustento_legal_normativo: e.target.value })}
                        className="w-full px-3 py-1.5 border border-slate-200 rounded-xl text-sm"
                      />
                    </div>
                  </div>
                ) : (
                  /* VIEW MODE */
                  <div className="space-y-4">
                    {/* Upper row: Tag metadata and actions */}
                    <div className="flex flex-wrap items-center justify-between gap-3 border-b border-slate-100 pb-3">
                      <div className="flex flex-wrap items-center gap-2">
                        <span className="text-sm font-mono font-bold text-indigo-600 bg-indigo-50 px-2.5 py-1 rounded-lg">
                          {riesgo.numero_riesgo}
                        </span>
                        <span className="text-xs font-bold text-slate-500 bg-slate-100 px-2.5 py-1 rounded-lg">
                          {riesgo.sector}
                        </span>
                        <span className="text-xs font-bold text-slate-500 bg-slate-100 px-2.5 py-1 rounded-lg">
                          {riesgo.tipo_contrato}
                        </span>
                        <span className="text-xs font-bold text-indigo-500 bg-indigo-50 px-2.5 py-1 rounded-lg">
                          {riesgo.categoria}
                        </span>
                        {riesgo.subcategoria && (
                          <span className="text-xs font-semibold text-indigo-500/80 bg-indigo-50/50 px-2.5 py-1 rounded-lg border border-indigo-100">
                            {riesgo.subcategoria}
                          </span>
                        )}
                        <span className={`text-[10px] font-extrabold px-2 py-0.5 rounded-full ${
                          riesgo.nivel_sustento_documental === 'ALTO' ? 'bg-emerald-100 text-emerald-800' :
                          riesgo.nivel_sustento_documental === 'MEDIO' ? 'bg-amber-100 text-amber-800' :
                          riesgo.nivel_sustento_documental === 'BAJO' ? 'bg-rose-100 text-rose-800' : 'bg-slate-100 text-slate-800'
                        }`}>
                          Sustento: {riesgo.nivel_sustento_documental || 'MANUAL'}
                        </span>
                      </div>

                      {/* Item Actions */}
                      <div className="flex items-center gap-1">
                        <button
                          onClick={() => handleStartEdit(riesgo)}
                          className="p-1.5 text-slate-400 hover:text-slate-600 hover:bg-slate-50 rounded-lg transition-colors cursor-pointer"
                          title="Editar Riesgo"
                        >
                          <Edit2 className="w-4 h-4" />
                        </button>
                        <button
                          onClick={() => handleDelete(riesgo.numero_riesgo)}
                          className="p-1.5 text-slate-400 hover:text-rose-600 hover:bg-rose-50 rounded-lg transition-colors cursor-pointer"
                          title="Eliminar de Biblioteca"
                        >
                          <Trash2 className="w-4 h-4" />
                        </button>
                      </div>
                    </div>

                    {/* Main texts */}
                    <div className="grid grid-cols-1 md:grid-cols-12 gap-5 pt-1">
                      {/* Left: Risk Text */}
                      <div className="md:col-span-7 space-y-2">
                        <h4 className="text-xs font-bold text-slate-400 uppercase tracking-widest">Riesgo Identificado</h4>
                        <p className="text-slate-800 font-semibold text-sm sm:text-base leading-relaxed whitespace-pre-line">
                          {riesgo.riesgo_identificado}
                        </p>
                        {riesgo.alerta_sistema && (
                          <div className="flex items-start gap-2 text-xs bg-slate-50 text-slate-600 p-3 rounded-xl border border-slate-100 mt-3">
                            <AlertCircle className="w-4 h-4 text-indigo-500 mt-0.5 shrink-0" />
                            <span><strong>Observación:</strong> {riesgo.alerta_sistema}</span>
                          </div>
                        )}
                      </div>

                      {/* Right: Sustento text */}
                      <div className="md:col-span-5 bg-slate-50/50 border border-slate-100 rounded-xl p-4 space-y-2">
                        <h4 className="text-xs font-bold text-slate-400 uppercase tracking-widest">Sustento Legal y Contexto</h4>
                        {riesgo.sustento_legal_normativo ? (
                          <p className="text-slate-600 text-xs sm:text-sm leading-relaxed whitespace-pre-line">
                            {riesgo.sustento_legal_normativo}
                          </p>
                        ) : (
                          <p className="text-slate-400 text-xs italic">
                            No se ingresó sustento legal para este riesgo.
                          </p>
                        )}

                        {/* File names and locations if available */}
                        {(riesgo.nombre_archivo_licitacion || riesgo.nombre_archivo_normativa) && (
                          <div className="text-[10px] text-slate-400 space-y-1 pt-2 border-t border-slate-100/60 mt-2">
                            {riesgo.nombre_archivo_licitacion && (
                              <p className="truncate"><strong>Licitación:</strong> {riesgo.nombre_archivo_licitacion} {riesgo.pagina_pdf ? `(Pág. ${riesgo.pagina_pdf})` : ''}</p>
                            )}
                            {riesgo.nombre_archivo_normativa && (
                              <p className="truncate"><strong>Normativa:</strong> {riesgo.nombre_archivo_normativa}</p>
                            )}
                          </div>
                        )}
                      </div>
                    </div>
                  </div>
                )}
              </div>
            );
          })}
        </div>
      )}
    </div>
  );
}
